# Generated by Django 4.2.11 on 2024-04-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='criminal_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
