# Generated by Django 4.2.11 on 2024-04-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0002_alter_criminal_criminal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('alias_id', models.IntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=20)),
                ('criminal', models.ForeignKey(db_column='criminal_id', on_delete=django.db.models.deletion.CASCADE, to='jail.criminal')),
            ],
        ),
    ]
