# Generated by Django 4.2.11 on 2024-04-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0003_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbationOfficer',
            fields=[
                ('prob_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='alias',
            name='criminal',
        ),
        migrations.AddField(
            model_name='alias',
            name='criminal_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jail.criminal'),
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('classification', models.CharField(default='U', max_length=1)),
                ('date_charged', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=2)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('appeal_cut_date', models.DateField(blank=True, null=True)),
                ('criminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.criminal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='crime',
            constraint=models.CheckConstraint(check=models.Q(('hearing_date__gt', models.F('date_charged'))), name='hearing_date_gt_date_charged'),
        ),
    ]
