# Generated by Django 4.2.11 on 2024-04-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0004_probationofficer_remove_alias_criminal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCodes',
            fields=[
                ('crime_code', models.IntegerField(primary_key=True, serialize=False)),
                ('code_description', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=10)),
                ('precinct', models.CharField(max_length=4)),
                ('badge', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('violations', models.IntegerField()),
                ('criminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.criminal')),
                ('prob_officer', models.ForeignKey(db_column='prob_id', on_delete=django.db.models.deletion.CASCADE, to='jail.probationofficer')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.crime')),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.officer')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeCharge',
            fields=[
                ('charge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('charge_status', models.CharField(max_length=2)),
                ('fine_amount', models.IntegerField(blank=True, null=True)),
                ('court_fee', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('pay_due_date', models.DateField(blank=True, null=True)),
                ('crime_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.crimecodes')),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.crime')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_gt_start_date'),
        ),
        migrations.AddConstraint(
            model_name='crimeofficer',
            constraint=models.UniqueConstraint(models.F('crime_id'), models.F('officer_id'), name='primary_key'),
        ),
    ]
