# Generated by Django 4.2.11 on 2024-04-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0005_crimecodes_officer_sentence_crimeofficer_crimecharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('appeal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='P', max_length=1)),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.crime')),
            ],
        ),
    ]
