# Generated by Django 4.2.11 on 2024-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0006_appeal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crimeofficer',
            name='primary_key',
        ),
        migrations.AddConstraint(
            model_name='crimeofficer',
            constraint=models.UniqueConstraint(fields=('crime_id', 'officer_id'), name='primary_key'),
        ),
    ]
