# Generated by Django 4.2.11 on 2024-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0007_remove_crimeofficer_primary_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='alias_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crimecharge',
            name='charge_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crimecodes',
            name='crime_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='criminal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officer',
            name='officer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='probationofficer',
            name='prob_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
