# Generated by Django 4.2.11 on 2024-04-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0008_alter_alias_alias_id_alter_appeal_appeal_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='criminal_id',
            new_name='criminal',
        ),
        migrations.RenameField(
            model_name='appeal',
            old_name='crime_id',
            new_name='crime',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='criminal_id',
            new_name='criminal',
        ),
        migrations.RenameField(
            model_name='crimecharge',
            old_name='crime_id',
            new_name='crime',
        ),
        migrations.RenameField(
            model_name='crimeofficer',
            old_name='crime_id',
            new_name='crime',
        ),
        migrations.RenameField(
            model_name='crimeofficer',
            old_name='officer_id',
            new_name='officer',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='criminal_id',
            new_name='criminal',
        ),
    ]
