# Generated by Django 4.2.11 on 2024-04-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0009_rename_criminal_id_alias_criminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='classification',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('O', 'O'), ('U', 'U')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('CL', 'Cl'), ('CA', 'Ca'), ('IA', 'Ia')], max_length=2),
        ),
    ]
