# Generated by Django 4.2.11 on 2024-04-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0010_alter_crime_classification_alter_crime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('P', 'P'), ('A', 'A'), ('D', 'D')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='crimecharge',
            name='charge_status',
            field=models.CharField(choices=[('PD', 'Pd'), ('GL', 'Gl'), ('NG', 'Ng')], max_length=2),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='p_status',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='v_status',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='probationofficer',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='type',
            field=models.CharField(choices=[('J', 'J'), ('H', 'H'), ('P', 'P')], max_length=1),
        ),
    ]
