# Generated by Django 4.2.11 on 2024-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0011_alter_appeal_status_alter_crimecharge_charge_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crime',
            name='hearing_date_gt_date_charged',
        ),
        migrations.RemoveConstraint(
            model_name='sentence',
            name='end_date_gt_start_date',
        ),
        migrations.AddConstraint(
            model_name='crime',
            constraint=models.CheckConstraint(check=models.Q(('hearing_date__gt', models.F('date_charged'))), name='hearing_date_gt_date_charged', violation_error_message='Hearing date must be greater than date charged.'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_gt_start_date', violation_error_message='End date must be greater than start date.'),
        ),
    ]
