# Generated by Django 4.2.11 on 2024-04-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0012_remove_crime_hearing_date_gt_date_charged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='prob_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jail.probationofficer'),
        ),
    ]
