# Generated by Django 4.2.11 on 2024-04-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0013_alter_sentence_prob_officer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrimeCodes',
            new_name='CrimeCode',
        ),
    ]
