# Generated by Django 4.2.11 on 2024-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jail', '0014_rename_crimecodes_crimecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='crimeofficer',
            name='primary_key',
        ),
        migrations.AddConstraint(
            model_name='crimeofficer',
            constraint=models.UniqueConstraint(fields=('crime_id', 'officer_id'), name='primary_key', violation_error_message='The crime and officer pair already exists.'),
        ),
    ]
